import pyautogui
import time

time.sleep(1)
pyautogui.click(pyautogui.locateCenterOnScreen('cfdicon.png', confidence=0.95))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('wall calc.png', confidence=0.9))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('chaejuk.png', confidence=0.9))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('forec.png', confidence=0.95))
time.sleep(0.5)
coord = pyautogui.locateCenterOnScreen('micronewton.png', confidence=0.95)
pyautogui.moveTo(coord, duration = 0.3)
pyautogui.click()
time.sleep(0.5)
coord = pyautogui.locateCenterOnScreen('newton.png', confidence=0.95)
pyautogui.moveTo(coord, duration = 0.3)
pyautogui.click()
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('torque.png', confidence=0.9))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('microNmm.png', confidence=0.95))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('Nm.png', confidence=0.95))


time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('chuksangjum.png', confidence=0.95))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('Xcoord.png', confidence=0.95))
pyautogui.hotkey('ctrl', 'a')
pyautogui.press("backspace")
pyautogui.write('90')
pyautogui.click(pyautogui.locateCenterOnScreen('Ycoord.png', confidence=0.95))
pyautogui.hotkey('ctrl', 'a')
pyautogui.press("backspace")
pyautogui.write('110')
pyautogui.click(pyautogui.locateCenterOnScreen('Zcoord.png', confidence=0.95))
pyautogui.hotkey('ctrl', 'a')
pyautogui.press("backspace")
pyautogui.write('150')

time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('ok.png', confidence=0.95))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('dir.png', confidence=0.95))
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('Xdir0.png', confidence=0.95))
pyautogui.hotkey('ctrl', 'a')
pyautogui.press("backspace")
pyautogui.write('1')
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('Zdir1.png', confidence=0.95))
pyautogui.hotkey('ctrl', 'a')
pyautogui.press("backspace")
pyautogui.write('0')
time.sleep(0.5)
pyautogui.click(pyautogui.locateCenterOnScreen('ok.png', confidence=0.95))

time.sleep(1)
pyautogui.click(pyautogui.locateCenterOnScreen('gyesan.png', confidence=0.95))